# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1152760f6e88d154f8771e5b4cac12be6bbfd4624b9e1d41111f8dd27532a640b898513fcfdd75fa8e8827ef6af8707d26cd362f459645b2964c8252a0f1444a

test:
  secret_key_base: 37ec7289de0c72cabb0f57ed8d371a027127b6c5e34ee4ae079fa85176ca439f7353224d7e17ee28ed0924e9285dda64371f3f75c53a2345c1120353ebd27863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
