# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7daf3a88a5b1586ce44238d5b8508370250b949700744ccc2e62ffd91e328814c3d032577f1e9920e7b9ec2f200abf8ed5b7843f91c243f1cdfa21d2529747b

test:
  secret_key_base: 8102be5de1a13050cbabb5056327423a1fc5a0a263931c645143ccb8a17bb8479d05bbc2e7ebd8c99a277e835bd02d6f095d81afe45e5652f09175a7dc1cee58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
