# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 046a2385bf2389db6ab391bf7cb6cbd5361e196af7a5ee1bdf5b655fe6fbc078b5e8043d861980ad38bce680d9329af5e768cb6fe310b6387d0dd5e0bf9d8149

test:
  secret_key_base: 5b5055a9bb4f2150168a0d02a67441da613b8acd115d206edf08d4e78ae7f710f98fd0fb5916134efda8cd0fae20020848c651f387d17528921bc2e7670efe5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
