# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0ea32e9681a062f9c4c3bedfa48132bb87d28dc1022d4428ab9c619bccdef4310c5d6e3a3e25cc7e8e56f1bdb0df12ed2a13c7cb6833fcbc00541f3470813e

test:
  secret_key_base: 8dfd97f864f85f001c07b237197eec091c53996528a9dcf3cd9d793b94adcd0d29022ed8083f0acfc3f88e8a19fb81f3141623a96cec60e055a7977ad24652f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
